// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/order/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Models
type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "confirmed", "cancelled", "completed"
	Items              []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount        float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CancellationReason string                 `protobuf:"bytes,8,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Request/Response
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateOrderResponse_OrderId
	//	*CreateOrderResponse_Error
	Result        isCreateOrderResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderResponse) GetResult() isCreateOrderResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateOrderResponse) GetOrderId() int64 {
	if x != nil {
		if x, ok := x.Result.(*CreateOrderResponse_OrderId); ok {
			return x.OrderId
		}
	}
	return 0
}

func (x *CreateOrderResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CreateOrderResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateOrderResponse_Result interface {
	isCreateOrderResponse_Result()
}

type CreateOrderResponse_OrderId struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3,oneof"`
}

type CreateOrderResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateOrderResponse_OrderId) isCreateOrderResponse_Result() {}

func (*CreateOrderResponse_Error) isCreateOrderResponse_Result() {}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CancelOrderResponse_Success
	//	*CancelOrderResponse_Error
	Result        isCancelOrderResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderResponse) GetResult() isCancelOrderResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CancelOrderResponse) GetSuccess() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Result.(*CancelOrderResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *CancelOrderResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CancelOrderResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCancelOrderResponse_Result interface {
	isCancelOrderResponse_Result()
}

type CancelOrderResponse_Success struct {
	Success *emptypb.Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type CancelOrderResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CancelOrderResponse_Success) isCancelOrderResponse_Result() {}

func (*CancelOrderResponse_Error) isCancelOrderResponse_Result() {}

type UpdateOrderRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderId            int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // для проверки ownership
	Status             *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	CancellationReason *string                `protobuf:"bytes,4,opt,name=cancellation_reason,json=cancellationReason,proto3,oneof" json:"cancellation_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOrderRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateOrderRequest) GetCancellationReason() string {
	if x != nil && x.CancellationReason != nil {
		return *x.CancellationReason
	}
	return ""
}

type UpdateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateOrderResponse_Success
	//	*UpdateOrderResponse_Error
	Result        isUpdateOrderResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrderResponse) GetResult() isUpdateOrderResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateOrderResponse) GetSuccess() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Result.(*UpdateOrderResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *UpdateOrderResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdateOrderResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateOrderResponse_Result interface {
	isUpdateOrderResponse_Result()
}

type UpdateOrderResponse_Success struct {
	Success *emptypb.Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type UpdateOrderResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateOrderResponse_Success) isUpdateOrderResponse_Result() {}

func (*UpdateOrderResponse_Error) isUpdateOrderResponse_Result() {}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetOrderResponse_Order
	//	*GetOrderResponse_Error
	Result        isGetOrderResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderResponse) GetResult() isGetOrderResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		if x, ok := x.Result.(*GetOrderResponse_Order); ok {
			return x.Order
		}
	}
	return nil
}

func (x *GetOrderResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetOrderResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetOrderResponse_Result interface {
	isGetOrderResponse_Result()
}

type GetOrderResponse_Order struct {
	Order *Order `protobuf:"bytes,1,opt,name=order,proto3,oneof"`
}

type GetOrderResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetOrderResponse_Order) isGetOrderResponse_Result() {}

func (*GetOrderResponse_Error) isGetOrderResponse_Result() {}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from_date,json=fromDate,proto3,oneof" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to_date,json=toDate,proto3,oneof" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserOrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserOrdersRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetUserOrdersRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetUserOrdersRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetUserOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserOrdersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetOrderStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatsRequest) Reset() {
	*x = GetOrderStatsRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatsRequest) ProtoMessage() {}

func (x *GetOrderStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderStatsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders   int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	ActiveOrders  int32                  `protobuf:"varint,2,opt,name=active_orders,json=activeOrders,proto3" json:"active_orders,omitempty"`
	TotalSpent    float64                `protobuf:"fixed64,3,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	LastOrderDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_order_date,json=lastOrderDate,proto3" json:"last_order_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatsResponse) Reset() {
	*x = GetOrderStatsResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatsResponse) ProtoMessage() {}

func (x *GetOrderStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderStatsResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *GetOrderStatsResponse) GetActiveOrders() int32 {
	if x != nil {
		return x.ActiveOrders
	}
	return 0
}

func (x *GetOrderStatsResponse) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *GetOrderStatsResponse) GetLastOrderDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastOrderDate
	}
	return nil
}

var File_api_order_v1_order_proto protoreflect.FileDescriptor

const file_api_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x18api/order/v1/order.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbd\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12)\n" +
	"\x05items\x18\x04 \x03(\v2\x13.order.v1.OrderItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\x13cancellation_reason\x18\b \x01(\tR\x12cancellationReason\"\x7f\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\"\xa9\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\adetails\x18\x03 \x03(\v2\x1c.order.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.order.v1.OrderItemR\x05items\"e\n" +
	"\x13CreateOrderResponse\x12\x1b\n" +
	"\border_id\x18\x01 \x01(\x03H\x00R\aorderId\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.order.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"`\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"|\n" +
	"\x13CancelOrderResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\asuccess\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.order.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xbe\x01\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x124\n" +
	"\x13cancellation_reason\x18\x04 \x01(\tH\x01R\x12cancellationReason\x88\x01\x01B\t\n" +
	"\a_statusB\x16\n" +
	"\x14_cancellation_reason\"|\n" +
	"\x13UpdateOrderResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\asuccess\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.order.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"n\n" +
	"\x10GetOrderResponse\x12'\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderH\x00R\x05order\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.order.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x9a\x02\n" +
	"\x14GetUserOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x00R\x06status\x88\x01\x01\x12<\n" +
	"\tfrom_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bfromDate\x88\x01\x01\x128\n" +
	"\ato_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06toDate\x88\x01\x01B\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_date\"\x92\x01\n" +
	"\x15GetUserOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"/\n" +
	"\x14GetOrderStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xc4\x01\n" +
	"\x15GetOrderStatsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12#\n" +
	"\ractive_orders\x18\x02 \x01(\x05R\factiveOrders\x12\x1f\n" +
	"\vtotal_spent\x18\x03 \x01(\x01R\n" +
	"totalSpent\x12B\n" +
	"\x0flast_order_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastOrderDate2\xd9\x03\n" +
	"\fOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\x12J\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1d.order.v1.CancelOrderResponse\x12J\n" +
	"\vUpdateOrder\x12\x1c.order.v1.UpdateOrderRequest\x1a\x1d.order.v1.UpdateOrderResponse\x12A\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\x12P\n" +
	"\rGetUserOrders\x12\x1e.order.v1.GetUserOrdersRequest\x1a\x1f.order.v1.GetUserOrdersResponse\x12P\n" +
	"\rGetOrderStats\x12\x1e.order.v1.GetOrderStatsRequest\x1a\x1f.order.v1.GetOrderStatsResponseB\x1cZ\x1aorder-service/api/order/v1b\x06proto3"

var (
	file_api_order_v1_order_proto_rawDescOnce sync.Once
	file_api_order_v1_order_proto_rawDescData []byte
)

func file_api_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)))
	})
	return file_api_order_v1_order_proto_rawDescData
}

var file_api_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_order_v1_order_proto_goTypes = []any{
	(*Order)(nil),                 // 0: order.v1.Order
	(*OrderItem)(nil),             // 1: order.v1.OrderItem
	(*Error)(nil),                 // 2: order.v1.Error
	(*CreateOrderRequest)(nil),    // 3: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 4: order.v1.CreateOrderResponse
	(*CancelOrderRequest)(nil),    // 5: order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 6: order.v1.CancelOrderResponse
	(*UpdateOrderRequest)(nil),    // 7: order.v1.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),   // 8: order.v1.UpdateOrderResponse
	(*GetOrderRequest)(nil),       // 9: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 10: order.v1.GetOrderResponse
	(*GetUserOrdersRequest)(nil),  // 11: order.v1.GetUserOrdersRequest
	(*GetUserOrdersResponse)(nil), // 12: order.v1.GetUserOrdersResponse
	(*GetOrderStatsRequest)(nil),  // 13: order.v1.GetOrderStatsRequest
	(*GetOrderStatsResponse)(nil), // 14: order.v1.GetOrderStatsResponse
	nil,                           // 15: order.v1.Error.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_api_order_v1_order_proto_depIdxs = []int32{
	1,  // 0: order.v1.Order.items:type_name -> order.v1.OrderItem
	16, // 1: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: order.v1.Error.details:type_name -> order.v1.Error.DetailsEntry
	1,  // 4: order.v1.CreateOrderRequest.items:type_name -> order.v1.OrderItem
	2,  // 5: order.v1.CreateOrderResponse.error:type_name -> order.v1.Error
	17, // 6: order.v1.CancelOrderResponse.success:type_name -> google.protobuf.Empty
	2,  // 7: order.v1.CancelOrderResponse.error:type_name -> order.v1.Error
	17, // 8: order.v1.UpdateOrderResponse.success:type_name -> google.protobuf.Empty
	2,  // 9: order.v1.UpdateOrderResponse.error:type_name -> order.v1.Error
	0,  // 10: order.v1.GetOrderResponse.order:type_name -> order.v1.Order
	2,  // 11: order.v1.GetOrderResponse.error:type_name -> order.v1.Error
	16, // 12: order.v1.GetUserOrdersRequest.from_date:type_name -> google.protobuf.Timestamp
	16, // 13: order.v1.GetUserOrdersRequest.to_date:type_name -> google.protobuf.Timestamp
	0,  // 14: order.v1.GetUserOrdersResponse.orders:type_name -> order.v1.Order
	16, // 15: order.v1.GetOrderStatsResponse.last_order_date:type_name -> google.protobuf.Timestamp
	3,  // 16: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	5,  // 17: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	7,  // 18: order.v1.OrderService.UpdateOrder:input_type -> order.v1.UpdateOrderRequest
	9,  // 19: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	11, // 20: order.v1.OrderService.GetUserOrders:input_type -> order.v1.GetUserOrdersRequest
	13, // 21: order.v1.OrderService.GetOrderStats:input_type -> order.v1.GetOrderStatsRequest
	4,  // 22: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	6,  // 23: order.v1.OrderService.CancelOrder:output_type -> order.v1.CancelOrderResponse
	8,  // 24: order.v1.OrderService.UpdateOrder:output_type -> order.v1.UpdateOrderResponse
	10, // 25: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	12, // 26: order.v1.OrderService.GetUserOrders:output_type -> order.v1.GetUserOrdersResponse
	14, // 27: order.v1.OrderService.GetOrderStats:output_type -> order.v1.GetOrderStatsResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_order_v1_order_proto_init() }
func file_api_order_v1_order_proto_init() {
	if File_api_order_v1_order_proto != nil {
		return
	}
	file_api_order_v1_order_proto_msgTypes[4].OneofWrappers = []any{
		(*CreateOrderResponse_OrderId)(nil),
		(*CreateOrderResponse_Error)(nil),
	}
	file_api_order_v1_order_proto_msgTypes[6].OneofWrappers = []any{
		(*CancelOrderResponse_Success)(nil),
		(*CancelOrderResponse_Error)(nil),
	}
	file_api_order_v1_order_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_order_v1_order_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateOrderResponse_Success)(nil),
		(*UpdateOrderResponse_Error)(nil),
	}
	file_api_order_v1_order_proto_msgTypes[10].OneofWrappers = []any{
		(*GetOrderResponse_Order)(nil),
		(*GetOrderResponse_Error)(nil),
	}
	file_api_order_v1_order_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_order_v1_order_proto = out.File
	file_api_order_v1_order_proto_goTypes = nil
	file_api_order_v1_order_proto_depIdxs = nil
}
